name: Backend-Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [backend_deploy]

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: python version
      run: python --version
    - name: list directory
      run: ls -la
    - name: install packages
      run: pip install -r backend/requirements.txt
      
    - name: download dataset
      run: wget -O data/heart_disease.csv
    - name: cat dataset
      run: cat data/heart_disease.csv   
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        
    - name: Download dataset
      run: |
        mkdir -p data/IR-Plag-Dataset
        wget -O plagiarism_dataset.zip ${{github.event.client_payload.dataseturl}}
        unzip plagiarism_dataset.zip -d data/IR-Plag-Dataset
        
    - name: Train model
      run: python backend/model/train.py
      
    - name: Build Docker image
      run: docker build -t ${{secrets.DOCKER_USER}}/plagiarism-detector:${{github.event.client_payload.sha}} .
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_USER}}/plagiarism-detector:${{github.event.client_payload.sha}}
