name: backend
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [plagiarism_detection_ci_cd]

jobs:
  train_deploy_model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install javalang scikit-learn numpy pandas joblib
        
    - name: Train model
      run: |
        python backend/model/train.py
      env:
        DATASET_PATH: "/github/workspace/backend/data/IR-Plag-Dataset/"
        
    - name: Save model artifacts
      run: |
        mkdir -p model_artifacts
        cp backend/model/*.joblib model_artifacts/
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USER }}/clonbusters:latest,${{ secrets.DOCKER_USER }}/clonbusters:${{ github.sha }}

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USER }}/clonbusters:${{ github.sha }}
          docker stop clonbusters || true
          docker rm clonbusters || true
          docker run -d --name clonbusters -p 8000:8000 ${{ secrets.DOCKER_USER }}/clonbusters:${{ github.sha }}
