name: Clonbusters-ModelOpss
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [plagiarism_detection_ci_cd]

jobs:
  train_deploy_model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install javalang scikit-learn numpy pandas joblib
        
    - name: Verify dataset structure
      run: |
        ls -R backend/data/IR-Plag-Dataset/
        
    - name: Train model
      run: |
        python backend/model/train.py
      env:
        DATASET_PATH: "/github/workspace/backend/data/IR-Plag-Dataset/"
        
    - name: Save model artifacts
      run: |
        mkdir -p model_artifacts
        cp model/*.joblib model_artifacts/
        
    - name: Docker build
      run: |
        docker build -t ${{secrets.DOCKER_USER}}/clonbusters:${{ github.sha }} .
        
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Docker push
      run: |
        docker push ${{secrets.DOCKER_USER}}/clonbusters:${{ github.sha }}
