name: backend
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [plagiarism_detection_ci_cd]

jobs:
  train_deploy_model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install javalang scikit-learn numpy pandas joblib
        
    - name: List directory structure
      run: |
        echo "Current directory structure:"
        ls -R
        
    - name: Create directories
      run: |
        mkdir -p backend/model
        mkdir -p data/IR-Plag-Dataset
        
    - name: Verify dataset location
      run: |
        echo "Checking dataset location..."
        ls -la data/IR-Plag-Dataset || echo "Dataset directory is empty"
        
    - name: Train model
      run: |
        cd backend
        python model/train.py
      env:
        DATASET_PATH: "../data/IR-Plag-Dataset"
        
    - name: Verify model artifacts
      run: |
        echo "Checking model artifacts..."
        ls -la backend/model/
        
    - name: Save model artifacts
      uses: actions/upload-artifact@v2
      with:
        name: model-artifacts
        path: |
          backend/model/*.joblib
          backend/model/*.json
