name: backend
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [plagiarism_detection_ci_cd]

jobs:
  train_deploy_model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install javalang scikit-learn numpy pandas joblib
        
    - name: List initial directory structure
      run: |
        echo "Initial directory structure:"
        ls -R
        
    - name: Create and verify backend directories
      run: |
        mkdir -p backend/data/IR-Plag-Dataset
        mkdir -p backend/model
        echo "Created directories structure:"
        ls -R backend/
        
    # Asumiendo que el dataset está en el repositorio en la carpeta correcta
    - name: Verify dataset location
      run: |
        echo "Dataset location check:"
        if [ -d "backend/data/IR-Plag-Dataset" ]; then
          echo "Dataset directory exists"
          ls -la backend/data/IR-Plag-Dataset
        else
          echo "Dataset directory not found"
          exit 1
        fi
        
    - name: Train model
      run: |
        cd backend
        echo "Current directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
        python model/train.py
      env:
        DATASET_PATH: "data/IR-Plag-Dataset"
        
    - name: Verify model artifacts
      run: |
        echo "Checking model artifacts..."
        ls -la backend/model/
        
    - name: Save model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-artifacts
        path: |
          backend/model/*.joblib
          backend/model/*.json
        retention-days: 90