# .github/workflows/backend.yml
name: backend
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [plagiarism_detection_ci_cd]

jobs:
  train_deploy_model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install javalang scikit-learn numpy pandas joblib
        
    - name: Create model directory
      run: mkdir -p backend/model
        
    - name: Train model
      run: |
        cd backend
        python model/train.py
      env:
        DATASET_PATH: "data/IR-Plag-Dataset/"
        
    - name: Save model artifacts
      run: |
        mkdir -p model_artifacts
        cp backend/model/*.joblib model_artifacts/ || echo "No joblib files found"
        ls -la backend/model/
        ls -la model_artifacts/

