name: frontend
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Docker build
        run: |
          docker build -t ${{secrets.DOCKER_USER}}/clonbusters-frontend:${{ github.sha }} -f frontend/Dockerfile .

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker push
        run: |
          docker push ${{secrets.DOCKER_USER}}/clonbusters-frontend:${{ github.sha }}
